### ISSUE TITLE
KeyError: “Can’t open attribute (Can’t locate attribute: ‘layer_names’)

### ISSUE THREAD

**Issue by shubhpy** [aleju/face-comparer#2]
**model.load_weights("../face-comparer/experiments/weights/example_experiment.last.weights"")**
```
Traceback (most recent call last):
  File "compare.py", line 40, in <module>
    compare(root + "bo1.jpg",root+"bo2.jpg")
  File "compare.py", line 13, in compare
    model.load_weights("../face-comparer/experiments/weights/example_experiment.last.weights"")
  File "/home/shubhanshu/ml-python/lib/python3.5/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/shubhanshu/ml-python/lib/python3.5/site-packages/keras/engine/topology.py", line 3103, in load_weights_from_hdf5_group
    layer_names = [n.decode('utf8') for n in f.attrs['layer_names']]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/shubhanshu/ml-python/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'layer_names')"
```
Above Bold line is throwing the above keyerror when example_experiments weights are used but with new weights, it worked.

Can someone please upload correct weights?
I do not have a "decent machine" to run all 1000*1000 epoch iterations

Thanks

**Comment by aleju** [comment]
The Keras saving/loading functions have likely been changed since the weights file was created. Your options would be to downgrade Keras, try writing your own loading function that is backwards-compatible (not sure if possible) or rerun the training.
