### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by furkank75** [aleju/face-comparer#4]
i would like start the training with the following command: 
`python train.py "Testing1" --images="C:/Users/Furkan/Desktop/lfwcrop_grey/faces/"`

and the Error is:
```
Found 13233 images in filepath, resulting in theoretically max k*(k-1)=175099056 ordered or (k over 2)=k(k-1)/2=87549528 unordered pairs.
Found 5749 different persons
In total...
Traceback (most recent call last):
  File "train.py", line 559, in <module>
    main()
  File "train.py", line 123, in main
    exclude_images=list(), seed=SEED, verbose=True)
  File "C:\Users\Furkan\Desktop\face-comparer\utils\datasets.py", line 267, in get_image_pairs
    print(" {:>7} persons have 1 image.".format(count_persons(1, 2)))
  File "C:\Users\Furkan\Desktop\face-comparer\utils\datasets.py", line 258, in count_persons
    names = [name for name, images in images_by_person.iteritems() \
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'
```

**Comment by aleju** [comment]
This is very old code that was still written for python 2.7. You would have to rename that method call from `iteritems` to `items` as only the latter method exists in python 3+.
